### ISSUE TITLE
a little bit valgrind

### ISSUE THREAD

**Issue by NoelSabia** [Reptudn/minishell#116]

**Comment by Reptudn** [comment]
check auch mal im tester ob du minor issues findest die du fixen kannst @NoelSabia

**Comment by NoelSabia** [comment]
jo was den tester angeht, bekomme ich nicht zum laufen, was waren die genauen schritte? abgesehen davon spannt mich valgrind heute schon gut ein. Sollte dir aber noch eien andere Funktion auffallen, dann einfach neues Issue machen und ich kuemmere mich darum, weil Valgrind geht mir langsam auch aufn Keks xD

**Comment by Reptudn** [comment]
tester installieren erstmal und dann in dem terminal bleiben in dem des installiert wurde, wenn es in anderen terminals nach dem install nicht geht

`bash -c "$(curl -fsSL https://raw.githubusercontent.com/zstenger93/42_minishell_tester/master/install.sh)"`
