### ISSUE TITLE
mach mal Telegram Mensabot public

### ISSUE THREAD

**Issue by PaulicStudios** [Reptudn/minishell#124]

**Comment by Reptudn** [comment]
bist du sicher dass du den code wirklcih sehen willst? xD

**Comment by Reptudn** [comment]
aus gewissen gruenden kann ich das nicht machen fuers erste wegen etwas was ich dir nacher gerne sagen kann @PaulicStudios

**Comment by Reptudn** [comment]
bald gibts ne [api](https://github.com/Reptudn/heilbronn-mensa-api/tree/main) @PaulicStudios

**Comment by PaulicStudios** [comment]
oha
