### ISSUE TITLE
command into structs

### ISSUE THREAD

**Issue by Reptudn** [Reptudn/minishell#13]
- from the line get all the commands and the args for that command
- link next / prev command
- if there is an operator put it in the operator field in the sctruct

(no input validation -> when it get to the code which puts it into the structs the input is already valid. Doesnt mean the command exists tho)

- ich wuerde mir erst den segfault anschauen und probieren zu fixxen (segfault kommt von commands/command_handler erste if condition im while loop, hab ich also erstmal ausgecommented) ✅
- dann checken ob das erste struct richtig befuellt wird (ja wird es mehr oder minder, wenn wir das Issue mit echo fixxen!!)✅
- dann die weiteren structs befuellen ❌

**Comment by Reptudn** [comment]
git fetch origin
git checkout 13-command-into-structs

- danke ✅

**Comment by Reptudn** [comment]
lösch einach des if raus bei dem das valid input gechecked wird weil des mach ich dann in einem anderen [issue](https://github.com/Reptudn/minishell/issues/14)

- ok wurde aus utils/make_cmds.c rausgeloescht ✅

**Comment by NoelSabia** [comment]
btw mir ist aufgefallen, dass echo scheisse baut und wir ein for loop dadrinnen haben. Ich aendere das mal kurz

- sollte gefixxt sein, ich glaube du hast nur vergessen den for loop raus zu nehmen und eine newline am ende zu printen ✅
