### ISSUE TITLE
env

### ISSUE THREAD

**Issue by Reptudn** [Reptudn/minishell#130]

**Comment by Reptudn** [comment]
https://www.ibm.com/docs/en/aix/7.3?topic=e-env-command

do i have to be able to specify custom env vars?
like `env PATH=something PWD=something <command>`

@NoelSabia

**Comment by NoelSabia** [comment]
do i have to be able to specify custom env vars?
- ich bin mir nicht sicher ob ich dich richtig verstanden habe, aber ja PATH soll man auch assignen koennen oder wie meinst du das mit <command>?
@Reptudn

**Comment by Reptudn** [comment]
nein ich meine allgemein schau dir mal die docs einfach an

**Comment by NoelSabia** [comment]
so wie ich es verstanden habe ja, das ist aber schon echt selten dass sowas vorkommt, deswegen waere es nicht so schlimm, wenn es nicht funktioniert.
