### ISSUE TITLE
Big Problemo with echo

### ISSUE THREAD

**Issue by NoelSabia** [Reptudn/minishell#17]
Every command is doing what it is supposed to do except echo.
Problem:
In utils/make_cmds -> allocate cmd everything is read correctly in the 2D Array of char **args but if you try to read the same piece of memory in the function make_cmds the first word(s) are complete bs.

Example1 (works):
minishell ➜ echo "hello there"

allocate_cmds[0]: "hello
allocate_cmds[1]: there"

make_cmds[0]: "hello
make_cmds[1]: there"

OUTPUT: "hello there"

Example2(does not work):
minishell ➜ echo "hello there how are you doing"

allocate_cmds[0]: "hello
allocate_cmds[1]: there
allocate_cmds[2]: how
allocate_cmds[3]: are
allocate_cmds[4]: you
allocate_cmds[5]: doing"

make_cmds[0]: P��įU
make_cmds[1]: there
make_cmds[2]: how
make_cmds[3]: are
make_cmds[4]: you
make_cmds[5]: doing"

OUTPUT: P��įU there how are you doing"

**Comment by NoelSabia** [comment]
PS:
Following solutions were tried in the process of making this work:
- strdup -> calloc instead of malloc
- rewriting echo
- returnvalue from allocate_cmd changed
- reading the **args from different functions to figure out why the hell it overwrite(?) the memory

PPS: jep the problem is most likely in utils/make_cmds.c

**Comment by Reptudn** [comment]
its because of the arguments parsing
we will do that later
