### ISSUE TITLE
operator exectue handler

### ISSUE THREAD

**Issue by Reptudn** [Reptudn/minishell#30]
functions when to use when having an operator like >>

**Comment by NoelSabia** [comment]
Files to edit:
- handle_commands/delimiter.c
- handle_commands/redirect_in.c ✅ (Testcase for example: sort < input.txt (sortiert alphabetisch))
- handle_commands/redirect_out.c

**Comment by NoelSabia** [comment]
Also found an other error:
🪄  minishell ➜ echo hi
hi ���U
🪄  minishell ➜ echo uwu
uwu ���U
🪄  minishell ➜ lol
command not found: lol
🪄  minishell ➜ echo lol
lol ���U
- will be fixxed after testing everything

Update: fixed✅
