### ISSUE TITLE
build ast

### ISSUE THREAD

**Issue by Reptudn** [Reptudn/minishell#33]
instead of using our command structs we build an [AST](https://en.wikipedia.org/wiki/Abstract_syntax_tree) with tokens and priorities

### Priorities from high to low
1. **Parentheses `()`**
2. **Unary operators** (e.g., `-`, `!`)
3. **Multiplicative operators** (`*`, `/`, `%`)
4. **Additive operators** (`+`, `-`)
5. **Comparison operators** (`<`, `<=`, `>`, `>=`)
6. **Equality operators** (`==`, `!=`)
7. **Logical AND (`&&`)**
8. **Logical OR (`||`)**
9. **Assignment operators** (`=`, `+=`, `-=`)

**Comment by Reptudn** [comment]
git fetch origin
git checkout 33-build-ast

**Comment by Reptudn** [comment]
[SHUNTING YARD VISUALIZATION](https://somethingorotherwhatever.com/shunting-yard-animation/)

**Comment by NoelSabia** [comment]
CMD: ls -la && (echo yeet | wc -l) || sort < testfile.txt

OUTPUT: ls -la 
STACK: &&


OUTPUT: ls -la
STACK: && (

OUTPUT: ls -la echo yeet 
STACK: && ( |

OUTPUT: ls -la echo yeet wc-l 
STACK: && ( | )

OUTPUT: ls -la echo yeet wc-l | &&
STACK: ||

OUTPUT: ls -la echo yeet wc-l | && || sort
STACK: <

OUTPUT: ls -la echo yeet wc-l | && || sort testfile.txt <
STACK:
