### ISSUE TITLE
papa noels valgrind spielplatz

### ISSUE THREAD

**Issue by Reptudn** [Reptudn/minishell#59]

**Comment by NoelSabia** [comment]
Known issues:
- delimiter can cause a segv(i guess fixxed -> not able to reproduce)
- some leaks probably also from the delimiter with a few bytes def lost (fixed)
- double frees and uninitialized values (fixed)

- echo is doing things its not doing in the bash(!)
- ls non_existent_file | grep "error" echo "Exit status: $?"  Exit status $? isnt working as it should
