### ISSUE TITLE
quotes in quotes, remove parens, ...

### ISSUE THREAD

**Issue by Reptudn** [Reptudn/minishell#85]
- [x] when a quote is in a quote then dont remove those inside
- [x] when encountering open or close parens just remove them when splitting (only if they are not in quotes ofc)
- [ ] figure out how to correctly handle heredoc because as an example echo << EOF should just print a nl and cat << EOF the content of the heredoc. right now both just print the heredoc output because its saved inside an echo cmd
- [x] other stuff that were issues before...

**Comment by Reptudn** [comment]
### bash
<img width="764" alt="image" src="https://github.com/Reptudn/minishell/assets/87537789/9137bb2e-4aa9-4ba2-bfe3-a4f180afac30">



### minishell
<img width="470" alt="image" src="https://github.com/Reptudn/minishell/assets/87537789/b226e17f-f723-47f2-898e-11bfd22d78ea">

**Comment by Reptudn** [comment]
git fetch origin
git checkout 85-big-chungus-fixes

**Comment by NoelSabia** [comment]
when a quote is in a quote then dont remove those inside
 --------------------------------------------------------------------------------
 regarding this "problem" i dont think there is any problem. the reason for that is following:
 bash: echo "hi how"are you"
 > (basically acts like heredoc then so not wrong)
 it actually behaves the same in our shell. so no problemo

**Comment by Reptudn** [comment]
No there is an issue. You just got it wrong.

in bash:
![image](https://github.com/Reptudn/minishell/assets/87537789/9377f129-783c-4dbe-a70e-b5b4cc1ec0f4)

in minishell:
![image](https://github.com/Reptudn/minishell/assets/87537789/82f6d266-70d7-4fd7-b548-d2c5415be19d)

**Comment by Reptudn** [comment]
there is also an issue that i will fix that is when we get `echo '"$USER"'` and the split works correctly we get this in the end `echo "$USER"` that doesnt count as a variable cuz its directly surrounded by quotes
